---
output: 
  word_document:
    reference_docx: template.docx 
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, ft.keepnext = F)
library(MassWateR)
library(dplyr)
library(flextable)
library(lubridate)

set_flextable_defaults(font.size = 9, padding = 0)

warn <- FALSE

# results data
respth <- system.file('extdata/ExampleResults.xlsx', package = 'MassWateR')

# dqo accuracy data
accpth <- system.file('extdata/ExampleDQOAccuracy.xlsx', package = 'MassWateR')

# dqo completeness data
frecompth <- system.file('extdata/ExampleDQOFrequencyCompleteness.xlsx', package = 'MassWateR')

resdat <- readMWRresults(respth, runchk = F)
accdat <- readMWRacc(accpth, runchk = F)
frecomdat <- readMWRfrecom(frecompth, runchk = F)

dt <- format(Sys.Date(), "%B %d, %Y") 

resdatdt <- range(resdat$`Activity Start Date`)
resdatdt <- paste(month(resdatdt), day(resdatdt), year(resdatdt), sep = '/') %>% 
  paste(collapse = ' to ')
  

# table theme
thm <- function(x){
  flextable::colformat_double(x, na_str = '-') %>% 
    flextable::colformat_char(na_str = '-') %>% 
    flextable::border_inner() %>% 
    flextable::align(align = 'center', part = 'all') %>% 
    flextable::align(align = 'left', j = 1, part = 'all') %>% 
    flextable::fontsize(size = 7, part = 'all') %>% 
    flextable::padding(padding = 0, part = 'all')
}

wd <- 6.5
```

# QC Review

## Organization Name

<br>

`r dt`

<br>

Prepared by: ____________________________________________ 

<br>

QAPP version: ___________________________________________

<br>

### Data Quality Objectives

<br>

```{r}
flextable::flextable(frecomdat) %>% 
  thm %>%
  flextable::width(width = wd / ncol(frecomdat)) %>% 
  flextable::add_header_row(value = c('', 'Frequency %', ''), colwidths = c(1, 5, 1))
```

<br>

```{r}
flextable::flextable(accdat) %>% 
  thm %>% 
  flextable::width(width = 1, j = 1) %>% 
  flextable::width(width = (wd -1) / (ncol(accdat) - 1), j = 2:ncol(accdat)) 
```

<br><br><br><br>

Notes:
<br>
<br>_____________________________________________________________________________________
<br>
<br>_____________________________________________________________________________________

\newpage

### QC Frequencies for `r resdatdt`

<br>

```{r}
tabMWRfre(res = resdat, frecom = frecomdat, type = 'summary', warn = warn) %>% 
  flextable::width(width = wd / ncol_keys(.)) 
```

<br><br><br><br>

Notes:
<br>
<br>_____________________________________________________________________________________
<br>
<br>_____________________________________________________________________________________

<br><br><br><br>
<br><br><br><br>
<br><br><br><br>

```{r}
tabMWRfre(res = resdat, frecom = frecomdat, type = 'percent', warn = warn) %>% 
  flextable::width(width = wd / ncol_keys(.)) 
```

\newpage

### QC Accuracy Summary for `r resdatdt`

<br>

```{r}
tabMWRacc(res = resdat, acc = accdat, type = 'summary', warn = warn) %>% 
  flextable::width(width = wd / ncol_keys(.))
```

<br><br><br><br>

Notes:
<br>
<br>_____________________________________________________________________________________
<br>
<br>_____________________________________________________________________________________

<br><br><br><br>
<br><br><br><br>
<br><br><br><br>

```{r}
tabMWRacc(res = resdat, acc = accdat, type = 'percent', warn = warn, frecom = frecomdat) %>% 
  flextable::width(width = wd / ncol_keys(.))
```

\newpage

### Data Completeness for `r resdatdt`

<!-- ```{r, warning = T} -->
<!-- tabMWRcom(res = resdat, frecom = frecomdat, warn = warn) -->
<!-- ``` -->

<!-- \newpage -->

<!-- ### QC Raw Data -->

<!-- ```{r} -->
<!-- tab <- tabMWRacc(res = resdat, acc = accdat, type = 'individual', accchk = 'Field Blanks', warn = warn) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- tabMWRacc(res = resdat, acc = accdat, type = 'individual', accchk = 'Lab Blanks', warn = warn) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- tabMWRacc(res = resdat, acc = accdat, type = 'individual', accchk = 'Field Duplicates', warn = warn) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- tabMWRacc(res = resdat, acc = accdat, type = 'individual', accchk = 'Lab Duplicates', warn = warn) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- tabMWRacc(res = resdat, acc = accdat, type = 'individual', accchk = 'Lab Spikes', warn = warn) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- tabMWRacc(res = resdat, acc = accdat, type = 'individual', accchk = 'Instrument Checks', warn = warn) -->
<!-- ``` -->